spring:
  profiles:
    active: dev
  application:
    name: user-center

#  session-redis 的指定，默认为 none 即将数据存在内存中
  session:
    store-type: redis
    timeout: 86400

server:
  port: 8081
  servlet:
    context-path: /api

knife4j:
  enable: true
  openapi:
    title: overlap 接口文档
    description: "找搭子咯 ~"
    email: 3204864983@qq.com
    concat: ovta
    url: http://localhost:5173/
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.ov.controller
netty:
  port: 9501

